"""add notion_export_page_id to users

Revision ID: 41501d5183d8
Revises: c944e5fc5812
Create Date: 2026-06-01 16:18:15.126940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41501d5183d8'
down_revision: Union[str, None] = 'c944e5fc5812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('users', sa.Column('notion_export_page_id', sa.String(length=255), nullable=True))
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.drop_index('ix_users_telegram_id', table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index('ix_users_telegram_id', 'users', ['telegram_id'], unique=False)
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'notion_export_page_id')
    op.alter_column('messages', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
